# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 404af7e06466d11f004765a9279d006a4396376a309782ef078ba0c13da0828fc777c5c2fbea414d341705fb5116774476c61f32f47ca3ce18bc8455fa113e3f

test:
  secret_key_base: c50f4d43b539e255a478d0eeb30f174be03f80d1e95e2f55774cb44a1fe68da689cc9dc2fcb22715f59192a5473307c60b1f73b79aef1c8cb7941f3d9895ae00

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
